const questions = [
  // NIVEL 1: FÁCIL
  { id: 1, question: "¿Quién construyó el arca para salvarse del diluvio?", options: ["Moisés", "Noé", "Abraham", "David"], answer: 1, level: 1 },
  { id: 2, question: "¿Cuál es el primer libro de la Biblia?", options: ["Éxodo", "Salmos", "Apocalipsis", "Génesis"], answer: 3, level: 1 },
  { id: 3, question: "¿Con qué venció David al gigante Goliat?", options: ["Una espada", "Una lanza", "Una honda", "Un arco"], answer: 2, level: 1 },
  { id: 4, question: "¿Cuántos mandamientos entregó Dios a Moisés?", options: ["7", "12", "10", "40"], answer: 2, level: 1 },
  { id: 5, question: "¿Quién fue tragado por un gran pez?", options: ["Jonás", "Pedro", "Elías", "Pablo"], answer: 0, level: 1 },
  { id: 6, question: "¿En qué ciudad nació Jesús?", options: ["Nazaret", "Jerusalén", "Belén", "Roma"], answer: 2, level: 1 },
  { id: 7, question: "¿Quién era el hombre más fuerte de la Biblia?", options: ["Salomón", "Sansón", "Saúl", "Gedeón"], answer: 1, level: 1 },
  { id: 8, question: "¿Qué mar se abrió para pasar el pueblo de Israel?", options: ["Mar Muerto", "Mar Rojo", "Mar Mediterráneo", "Mar Caspio"], answer: 1, level: 1 },
  { id: 9, question: "¿Cuántos discípulos principales tenía Jesús?", options: ["10", "7", "12", "24"], answer: 2, level: 1 },
  { id: 10, question: "¿Quién fue el primer hombre creado por Dios?", options: ["Adán", "Abel", "Set", "Enoc"], answer: 0, level: 1 },
  { id: 11, question: "¿Qué animal habló a Eva en el Edén?", options: ["Un ave", "Una serpiente", "Un león", "Un cordero"], answer: 1, level: 1 },
  { id: 12, question: "¿Quién resucitó al tercer día de entre los muertos?", options: ["Lázaro", "Jesús", "Juan el Bautista", "Esteban"], answer: 1, level: 1 },
  { id: 13, question: "¿Cómo se llamaba la madre de Jesús?", options: ["Marta", "María", "Magdalena", "Salomé"], answer: 1, level: 1 },
  { id: 14, question: "¿Quién bautizó a Jesús en el río Jordán?", options: ["Pedro", "Juan el Bautista", "Pablo", "Santiago"], answer: 1, level: 1 },
  { id: 15, question: "¿Cuál es el último libro de la Biblia?", options: ["Malaquías", "Judas", "Apocalipsis", "Hechos"], answer: 2, level: 1 },
  { id: 16, question: "¿Quién fue el hermano de Moisés?", options: ["Aarón", "Josué", "Caleb", "Jacob"], answer: 0, level: 1 },
  { id: 17, question: "¿Qué usó David para calmar al rey Saúl?", options: ["Una flauta", "Un arpa", "Un tambor", "Canto"], answer: 1, level: 1 },
  { id: 18, question: "¿Quién caminó sobre las aguas hacia Jesús?", options: ["Juan", "Andrés", "Pedro", "Tomás"], answer: 2, level: 1 },
  { id: 19, question: "¿Cuántas plagas envió Dios a Egipto?", options: ["7", "12", "10", "3"], answer: 2, level: 1 },
  { id: 20, question: "¿Quién interpretó los sueños del Faraón?", options: ["Daniel", "José", "Moisés", "Abraham"], answer: 1, level: 1 },
  { id: 21, question: "¿Qué ciudad cayó después de que el pueblo gritara y tocara trompetas?", options: ["Babilonia", "Nínive", "Jericó", "Sodoma"], answer: 2, level: 1 },
  { id: 22, question: "¿Quién fue metido en un foso de leones?", options: ["Daniel", "José", "Jonás", "David"], answer: 0, level: 1 },
  { id: 23, question: "¿Qué alimento llovió del cielo para los israelitas?", options: ["Pan", "Maná", "Codornices", "Fruta"], answer: 1, level: 1 },
  { id: 24, question: "¿Cómo se llamaba el gigante que David derrotó?", options: ["Goliat", "Sansón", "Og", "Anac"], answer: 0, level: 1 },
  { id: 25, question: "¿En qué jardín vivían Adán y Eva?", options: ["Getsemaní", "Edén", "Betania", "Carmelo"], answer: 1, level: 1 },
  { id: 26, question: "¿Quién fue sacado de una cesta en el río Nilo?", options: ["Isaac", "Moisés", "José", "Samuel"], answer: 1, level: 1 },

  // NIVEL 2: MEDIA
  { id: 27, question: "¿Quién fue vendido por sus hermanos como esclavo?", options: ["José", "Benjamín", "Isaac", "Jacob"], answer: 0, level: 2 },
  { id: 28, question: "¿Qué usó Dios para crear a Eva?", options: ["Polvo", "Una costilla", "Una piedra", "Una rama"], answer: 1, level: 2 },
  { id: 29, question: "¿Quién es conocido como el 'Padre de la Fe'?", options: ["Abraham", "Isaac", "Juan", "Mateo"], answer: 0, level: 2 },
  { id: 30, question: "¿Cuál es el libro de la Biblia con más capítulos?", options: ["Génesis", "Isaías", "Proverbios", "Salmos"], answer: 3, level: 2 },
  { id: 31, question: "¿Cómo se llamaba la esposa de Abraham?", options: ["Raquel", "Sara", "Rebeca", "Miriam"], answer: 1, level: 2 },
  { id: 32, question: "¿Quién fue el sucesor de Moisés como líder de Israel?", options: ["Josué", "Caleb", "Aarón", "Gedeón"], answer: 0, level: 2 },
  { id: 33, question: "¿En qué idioma se escribió originalmente el Nuevo Testamento?", options: ["Hebreo", "Latín", "Griego", "Arameo"], answer: 2, level: 2 },
  { id: 34, question: "¿Qué apóstol era médico?", options: ["Mateo", "Lucas", "Juan", "Pedro"], answer: 1, level: 2 },
  { id: 35, question: "¿Quién fue el primer rey de Israel?", options: ["David", "Salomón", "Saúl", "Esdras"], answer: 2, level: 2 },
  { id: 36, question: "¿Cómo se llamaba la madre de Samuel?", options: ["Sefora", "Ana", "Isabel", "Marta"], answer: 1, level: 2 },

  // NIVEL 3: DIFÍCIL
  { id: 37, question: "¿Quién fue el primer mártir cristiano?", options: ["Pedro", "Santiago", "Esteban", "Pablo"], answer: 2, level: 3 },
  { id: 38, question: "¿Cuántos años duró el cautiverio de Israel en Babilonia?", options: ["40 años", "70 años", "100 años", "120 años"], answer: 1, level: 3 },
  { id: 39, question: "¿Cuál es el libro más corto del Antiguo Testamento?", options: ["Abdías", "Filemón", "Hageo", "Jonás"], answer: 0, level: 3 },
  { id: 40, question: "¿Cuál era el nombre babilónico de Daniel?", options: ["Sadrac", "Mesac", "Abed-nego", "Beltsasar"], answer: 3, level: 3 },
  { id: 41, question: "¿Quién fue el último rey de Judá antes del exilio?", options: ["Josías", "Sedequías", "Joaquín", "Ezequías"], answer: 1, level: 3 },
  { id: 42, question: "¿En qué monte le dio Dios los mandamientos a Moisés?", options: ["Monte Carmelo", "Monte Sinaí", "Monte Nebo", "Monte Hermón"], answer: 1, level: 3 },
  { id: 43, question: "¿Cuántos capítulos tiene el libro de Abdías?", options: ["1", "5", "10", "12"], answer: 0, level: 3 },
  { id: 44, question: "¿Quién escribió el libro de los Hechos de los Apóstoles?", options: ["Pablo", "Mateo", "Lucas", "Juan"], answer: 2, level: 3 }
];